version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    volumes:
      - .:/app
    environment:
      - MONGOCONN=mongodb://db:27017
      - DBNAME=Blogging
      - DBCOLLECTION=posts

  db:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=Blogging

volumes:
  mongo-data: